# This is a basic workflow to help you get started with Actions

name: Deploy to multi stage environments

# Controls when the action will run. 
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:            
      - name: Run the build
        run: echo Build ran successfully!
  
  DeployDev:
    name: Deploy to Dev Environment
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: Dev_Env
      url: 'http://dev.timjim.com'
    steps:
      - name: DeployDev
        run: echo Deploying to development environment
  
  DeployQA:
    name: Deploy to QA Envir
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: QA_Env
      url: 'http://qa.timjim.com'
    steps:
      - name: DeployQA
        run: echo Deploying to QA environment
      
  DeployProd:
      name: Deploy to Prod Environment
      needs: [DeployQA]
      runs-on: ubuntu-latest
      environment: 
        name: Prod_Env
        url: 'http://www.timjim.com'
      steps:
        - name: Deploy
          run: echo Deploying to production environment
